what: 'qm_atomic'
properties: 'charges'
batch_size: 100
gpu: [1]
data_location: '../datasets/qm137/'
seed: 42
valid_fraction: .2
logname: 'charges_20L_wide_def_16'
num_layers: 20
d_model: 256
nhead: 32
lr: 0.0002
dim_feedforward: 512
scheduler: 'const'
lr_patience: ~
es_patience: 100
checkpoint_root: './pretrainings_plt'
max_epochs: 2000