what: 'tdc'
batch_size: 32
gpu: [0]
task_indices: []
checkpoint_path: ~
freeze_encoder: False  
warmup_steps: -1
unfreeze_step: -1
max_epochs: 2000
seeding: 42
name_run: 'scratch_20L_wide_def_16p'
num_layers: 20
d_model: 256
nhead: 32
dim_feedforward: 512
lr: 0.0002
scheduler: 'cyclic'
factor: 10